### PR TITLE
Gamecard (3DSX, CXI) fixes

### LINKED ISSUE #45: Implement booting to HOME Menu with 3DSX files
The 3DSX gamecard adapter doesn't currently expose all data required by the HOME Menu to allow booting. For details, see gamecard.cpp: https://github.com/mikage-emu/mikage-dev/blob/08e87df6b09b838fc3cb46ac6a31abf0cf99fd7d/source/loader/gamecard.cpp#L121

At least an `.icon` section must be added to the ExeFS.

Note that the emulator will currently [reject 3DSX files](https://github.com/mikage-emu/mikage-dev/blob/08e87df6b09b838fc3cb46ac6a31abf0cf99fd7d/source/session.cpp#L49-L60) since this configuration is known not to work, so this code must be disabled when working on a fix. Once commented out, use this to test:
```sh
mikage homebrew.3dsx --launch_menu
```

### PR DESCRIPTION
**Pull request by ZeroSkill1**
Intends to fix #45, #46, and #47.

- Mikage can now boot into the HOME menu with 3DSX and CXI files.
- 3DSX / CXI files can now be launched from the HOME menu. This is accomplished by hooking into an NS command that is related to gamecard updates, effectively disabling the gamecart update process for these kinds of files.
- For 3DSX files, Mikage will now use a default icon (if the 3DSX does not come with its own icon data) and banner to show on the HOME menu.
- During the NAND bootstrapping process, the logo animation splash from the source gamecard image is extracted into Mikage's data directory, and is used when booting 3DSX files from the HOME Menu.
- Regular (.cci/.3ds) gamecart images will now show the correct icon on the HOME Menu instead of always the icon of the gamecard image used for the NAND boostrapping process.
- Fixed (in)visibility of "Manual" button on the HOME Menu when any title is selected, so that it is hidden when a manual is available and hidden when not.

### CODE REVIEW

File: source/loader/gamecard.cpp [hunk 1]
```diff
@@ -249,58 +1154,147 @@ class Adaptor3DSXToNCCH : public HLE::PXI::FS::File {
...
-            throw std::runtime_error("Failed to read 3DSX header");
+        if (std::get<0>(ret) != HLE::OS::RESULT_OK || std::get<1>(ret) != sizeof(dot3dsxheader)) {
+            throw Mikage::Exceptions::Invalid("Could not read 3DSX header");
         }
+        
+        // Read and validate header(s), populate SMDH data
+        if (dot3dsxheader.header_size == sizeof(FileFormat::Dot3DSX::Header)) {
+            icon_data.magic = { 'S', 'M', 'D', 'H' };
+            std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t> conversion;
+            std::u16string longname = conversion.from_bytes(filename ? filename.value() : "Homebrew Application");
```
Comment (neobrain) [inline source/loader/gamecard.cpp:1171]: If we keep this, we probably want to limit it to the actual filename (excluding paths), since even the long description only has room for 128 characters.

File: source/loader/gamecard.cpp [hunk 2]
```diff
@@ -249,58 +1154,147 @@ class Adaptor3DSXToNCCH : public HLE::PXI::FS::File {
...
+            std::u16string shortname = conversion.from_bytes("Homebrew Application");
+            std::u16string publisher = conversion.from_bytes("Homebrew");
+            
+            for (int i = 0; i < icon_data.application_titles.size(); i++) {
+                ranges::copy(longname, icon_data.application_titles[i].long_description.begin());
+                ranges::copy(shortname, icon_data.application_titles[i].short_description.begin());
```
Comment (neobrain) [inline source/loader/gamecard.cpp:1177]: Range APIs support copying to ranges, so I think you don't need to query iterators here:

```suggestion
                ranges::copy(shortname, icon_data.application_titles[i].short_description);
```

(existing code doesn't do this, but let's be better than past-me :))

File: source/loader/gamecard.cpp [hunk 3]
```diff
@@ -113,55 +147,926 @@ bool GameCardFromCCI::IsLoadableFile(int file_descriptor) {
...
  * Adaptor to make 3DSX files "look" like NCCHs.
  */
 class Adaptor3DSXToNCCH : public HLE::PXI::FS::File {
     std::unique_ptr<HLE::PXI::FS::File> file; // 3DSX source data
+    std::unique_ptr<HLE::PXI::FS::HostFile> logo_file;
 
-    // TODO: Actually store the memory in here!
+    FileFormat::Dot3DSX::Header dot3dsxheader = {};
+    std::optional<FileFormat::Dot3DSX::SecondaryHeader> dot3dsx_secondary_header;
+    std::optional<std::string> filename;
```
Comment (neobrain) [inline source/loader/gamecard.cpp:1036]: Are 3DSX files without SMDH files common enough to put up with the added complexity here? Or would this mostly apply to custom one-off test apps instead of proper applications people would download and run?

Notably this won't easily work on Android, which must access the file using a raw file descriptor only. I think I'd rather just have legacy 3DSX files show up with unbranded "Homebrew" labels instead to keep this simple.

File: source/platform/file_formats/ncch.hpp [hunk 4]
```diff
@@ -38,7 +38,37 @@ using MediaUnit32 = MediaUnit<uint32_t>;
...
+            Trial                = 4,
+            ExtendedSystemUpdate = 5,
+        };
+        
+        enum FormType {
+            NotAssigned            = 0,
+            SimpleContent          = 1,
+            ExecutableWithoutRomFS = 2,
+            Executable             = 3,
+        };
```
Comment (neobrain) [inline source/platform/file_formats/ncch.hpp:58]: These should be `enum class`es. Might be worth moving them one level up, into NCCHHeader, if that makes sense.

File: source/platform/file_formats/ncch.hpp [hunk 5]
```diff
@@ -38,7 +38,37 @@ using MediaUnit32 = MediaUnit<uint32_t>;
...
+        
+        BOOST_HANA_DEFINE_STRUCT(TypeFlags,
+            (uint8_t, raw)
+        );
+        
+        constexpr auto form_type() { return BitField::v3::MakeFieldOn<0, 2>(this); }
+        constexpr auto content_type() { return BitField::v3::MakeFieldOn<2, 6>(this); }
```
Comment (neobrain) [inline source/platform/file_formats/ncch.hpp:65]: BitField v3 supports an exposure type as the third parameter:
```suggestion
        constexpr auto form_type() { return BitField::v3::MakeFieldOn<0, 2, FormType>(this); }
        constexpr auto content_type() { return BitField::v3::MakeFieldOn<2, 6, ContentType>(this); }
```

File: source/platform/file_formats/ncch.hpp [hunk 6]
```diff
@@ -466,14 +497,45 @@ struct NCSDHeader {
...
+        BOOST_HANA_DEFINE_STRUCT(NANDHeader,
+            (std::array<uint8_t, 0x5E>, unknown),
+            (std::array<uint8_t, 0x42>, encrypted_twl_mbr)
+        );
+        
+        struct Tags : expected_size_tag<0xA0> {};
+    };
+    
+    union NCSDExtendedHeader {
+        BOOST_HANA_DEFINE_STRUCT(NCSDExtendedHeader,
```
Comment (neobrain) [inline source/platform/file_formats/ncch.hpp:524]: Does any other code use `BOOST_HANA_DEFINE_STRUCT` with unions? Seems like this should just be a plain union (without the Tags as well). If this is required to compile, I'm not sure it will actually have reliable behavior in practice.

File: source/platform/file_formats/ncch.hpp [hunk 7]
```diff
@@ -466,14 +497,45 @@ struct NCSDHeader {
...
         );
     };
+    
+    struct CartHeader {
+        BOOST_HANA_DEFINE_STRUCT(CartHeader,
+            (std::array<uint8_t, 32>, exheader_sha256),
+            (uint32_t, additional_header_size),
+            (uint32_t, sector0_offset),
+            (uint64_t, partition_flags),
+            (std::array<uint64_t, 8>, partition_id_table),
```
Comment (neobrain) [inline source/platform/file_formats/ncch.hpp:507]: Could you add a brief inline-comment for this? Something like "Non-zero if a partition of the given id exists"

File: source/platform/file_formats/ncch.hpp [hunk 8]
```diff
@@ -466,14 +497,45 @@ struct NCSDHeader {
...
+            (std::array<uint8_t, 0x30>, unknown)
+        );
+        
+        struct Tags : expected_size_tag<0xA0> {};
```
Comment (neobrain) [inline source/platform/file_formats/ncch.hpp:511]: Nit: Hex constants should be formatted as lowercase, but don't worry about it for code that is already written.

File: source/platform/file_formats/ncch.hpp [hunk 9]
```diff
@@ -466,14 +497,45 @@ struct NCSDHeader {
             (MediaUnit32, size)
         );
     };
+    
+    struct CartHeader {
+        BOOST_HANA_DEFINE_STRUCT(CartHeader,
+            (std::array<uint8_t, 32>, exheader_sha256),
+            (uint32_t, additional_header_size),
```
Comment (neobrain) [inline source/platform/file_formats/ncch.hpp:504]: If this refers to NCSDExtendedHeader, could you add a comment like this?

```suggestion
            (uint32_t, additional_header_size), // see NCSDExtendedHeader
```

File: source/platform/file_formats/ncch.hpp [hunk 10]
```diff
@@ -466,14 +497,45 @@ struct NCSDHeader {
...
+    };
 
     BOOST_HANA_DEFINE_STRUCT(NCSDHeader,
         (std::array<uint8_t, 0x100>, signature), // RSA-2048 SHA-256 signature of this header (starting from magic?)
         (std::array<uint8_t, 4>, magic),         // always "NCSD"
         (MediaUnit32, size),                     // total NCSD size
         (std::array<uint8_t, 0x18>, unknown),
         (std::array<Partition, 8>, partition_table),
-        (std::array<uint8_t, 0xa0>, unknown2)
+        (NCSDExtendedHeader, extended_header)
```
Comment (neobrain) [inline source/platform/file_formats/ncch.hpp:538]: Is this a commonly used name for this NCSD header? Otherwise, it's perhaps better to go with "NCSDSecondaryHeader" to avoid overloading the very 3ds-specific ExHeader term.

File: source/platform/file_formats/smdh.hpp [hunk 11]
```diff
@@ -0,0 +1,77 @@
...
+    struct SMDHEULAVersion {
+        BOOST_HANA_DEFINE_STRUCT(SMDHEULAVersion,
+            (uint8_t, minor),
+            (uint8_t, major)
+        );
+        
+        struct Tags : expected_size_tag<0x2> {};
+    };
+    
+    enum SMDHFlags : uint32_t {
```
Comment (neobrain) [inline source/platform/file_formats/smdh.hpp:32]:
```suggestion
    enum class SMDHFlags : uint32_t {
```

File: source/processes/fs.cpp [hunk 12]
```diff
@@ -2112,24 +2116,62 @@ decltype(HLE::OS::ServiceHelper::SendReply) FakeFS::UserCommandHandler(FakeThrea
...
-        if (/*media_type == MediaType::GameCard*/ true) {
-            thread.WriteTLS(0x80, IPC::CommandHeader::Make(0, 2, 0).raw);
-            thread.WriteTLS(0x84, RESULT_OK);
-            if (content_type == 1) {
-                thread.WriteTLS(0x88, Meta::to_underlying(Loader::NCSDPartitionId::UpdateData));
-            } else if (content_type == 2) {
-                thread.WriteTLS(0x88, Meta::to_underlying(Loader::NCSDPartitionId::Manual));
-            } else if (content_type == 3) {
-                thread.WriteTLS(0x88, Meta::to_underlying(Loader::NCSDPartitionId::DownloadPlayChild));
+        auto content_type = SpecialContentType { static_cast<SpecialContentType>(thread.ReadTLS(0x90) & 0xff) };
```
Comment (neobrain) [inline source/processes/fs.cpp:2122]:
```suggestion
        auto content_type = static_cast<SpecialContentType>(thread.ReadTLS(0x90) & 0xff);
```

File: source/processes/fs.cpp [hunk 13]
```diff
@@ -2112,24 +2116,62 @@ decltype(HLE::OS::ServiceHelper::SendReply) FakeFS::UserCommandHandler(FakeThrea
...
+                    break;
+                case Platform::FS::SpecialContentType::UpdateDataNew3DS:
+                    target_ncsd_id = Loader::NCSDPartitionId::UpdateDataNew3DS;
+                    break;
+                default:
+                    throw Mikage::Exceptions::Invalid("GetSpecialContentType: Invalid special content type {:#x}", Meta::to_underlying(content_type));
+            }
+            
+            auto gamecard = thread.GetOS().setup.gamecard.get();
+            assert(gamecard);
```
Comment (neobrain) [inline source/processes/fs.cpp:2143]: `assert` is the wrong tool here, since an emulated application could (theoretically) call GetSpecialContentType without a card inserted.

So this should either warrant a runtime-check with `Mikage::Exceptions::Invalid`, or it should be dropped in favor of just crashing with a nullptr access.

File: source/processes/ns_hpv.cpp [hunk 14]
```diff
@@ -208,6 +209,23 @@ struct NsService : SessionToPort {
...
             Session::OnRequest(hypervisor, thread, session, description);
         });
+        
+        dispatcher.DecodeRequest<NS::CardUpdateInitialize>([&](auto& response, uint32_t shared_mem_size, Handle /* shared_mem */) {
+            auto description = fmt::format( "CardUpdateInitialize, shared_mem_size={:#x}", shared_mem_size);
+            Session::OnRequest(hypervisor, thread, session, description);
+            
+            auto gamecard = thread.GetOS().setup.gamecard.get();
+            assert(gamecard);
+            // Disable card update process for 3DSX files, CXI files, and CCI images without an update partition
```
Comment (neobrain) [inline source/processes/ns_hpv.cpp:219]: Since HPV is normally used for introspection only, let's be explicit about what's happening here:
```suggestion
            // Override the request data to disable card update process for 3DSX files, CXI files, and CCI images without an update partition
```

File: source/processes/ns_hpv.cpp [hunk 15]
```diff
@@ -208,6 +209,23 @@ struct NsService : SessionToPort {
...
+            if (!gamecard->HasPartition(Loader::NCSDPartitionId::UpdateData)) {
+                thread.WriteTLS(0x80, 0xFFFE0000); // make NS think a bogus command is sent
+                
+                response.OnResponse([=](Hypervisor& hv, Thread& thread, Result result) {
+                    thread.WriteTLS(0x80, NS::CardUpdateInitialize::response_header);
+                    thread.WriteTLS(0x84, 0xc821180b); // "No card update required"
+                });
+            }
```
Comment (neobrain) [inline source/processes/ns_hpv.cpp:227]: Since HPV is normally used for introspection only, let's be even more explicit about what's happening here:
```suggestion
            // Disable card update process for 3DSX files, CXI files, and CCI images without an update partition
            if (!gamecard->HasPartition(Loader::NCSDPartitionId::UpdateData)) {
                // Change the request command ID to 0xFFFE0000 to make NS ignore the command.
                thread.WriteTLS(0x80, 0xFFFE0000);

                // Override the response data to indicate that no update is required
                response.OnResponse([=](Hypervisor&, Thread& thread, Result) {
                    thread.WriteTLS(0x80, NS::CardUpdateInitialize::response_header);
                    thread.WriteTLS(0x84, 0xc821180b); // "No card update required"
                });
            }
```

File: source/processes/pxi_fs.cpp [hunk 16]
```diff
@@ -457,8 +457,8 @@ std::cerr << "level3 offset: 0x" << std::hex << level3_offset << std::endl;*/
     }
 
     // Open the ExeFS section specified by the remainder of the file path
-    case 1:
-    case 2:
+    case 1: // exefs:/.code
+    case 2: // HOME Menu data (exefs:/{icon, banner, logo})
```
Comment (neobrain) [inline source/processes/pxi_fs.cpp:461]: Is there anything specific to HOME Menu about sub file type 2? Isn't it just a generic mechanism to access the icon/banner/logo?

Perhaps a more fitting comment is `exefs:/{...} (mainly used by HOME Menu)`?

**Review by neobrain — COMMENTED** [review]
That's a juicy change set! Got through a first review pass, doesn't look like we'll need any major changes though.

File: source/loader/gamecard.cpp [hunk 17]
```diff
@@ -249,58 +1154,147 @@ class Adaptor3DSXToNCCH : public HLE::PXI::FS::File {
...
-    }
-
-    FileFormat::Dot3DSX::Header Read3DSXHeader(HLE::PXI::FS::FileContext& context) {
-        // TODO: Use serialization interface instead
-        FileFormat::Dot3DSX::Header dot3dsxheader;
+        
         auto ret = file->Read(context, 0, sizeof(dot3dsxheader), HLE::PXI::FS::FileBufferInHostMemory(dot3dsxheader));
-        if (ret != HLE::OS::OS::ResultAnd<uint32_t> { HLE::OS::RESULT_OK, sizeof(dot3dsxheader) }) {
-            throw std::runtime_error("Failed to read 3DSX header");
+        if (std::get<0>(ret) != HLE::OS::RESULT_OK || std::get<1>(ret) != sizeof(dot3dsxheader)) {
```
[the remark this answers is not in the document]
Comment (ZeroSkill1) [reply source/loader/gamecard.cpp:1163]: There's no overload for operator== in tuple that allows comparison with `std::pair`. Maybe you meant `std::tuple` instead?

File: source/loader/gamecard.cpp [hunk 18]
```diff
@@ -113,55 +147,926 @@ bool GameCardFromCCI::IsLoadableFile(int file_descriptor) {
...
 
-    FileFormat::Dot3DSX::Header dot3dsxheader = {};
+    FileFormat::SMDH icon_data = {};
 
 public:
-    Adaptor3DSXToNCCH(std::unique_ptr<HLE::PXI::FS::File> file_3dsx) : file(std::move(file_3dsx)) {
+    Adaptor3DSXToNCCH(std::unique_ptr<HLE::PXI::FS::File> file_3dsx, Settings::Settings &settings, std::optional<std::string> filename_3dsx = std::nullopt) : file(std::move(file_3dsx)), filename(filename_3dsx) {
+        auto logger = std::make_shared<spdlog::logger>("dummy", std::make_shared<spdlog::sinks::null_sink_st>());
+        auto file_context = HLE::PXI::FS::FileContext { *logger };
+        logo_file = std::make_unique<HLE::PXI::FS::HostFile>(settings.get<Settings::PathDataDir>() + "/logolz.bin", HLE::PXI::FS::HostFile::Default);
```
[the remark this answers is not in the document]
Comment (neobrain) [reply source/loader/gamecard.cpp:1048]: How about simply `placeholder_logo.bin`?

File: source/loader/gamecard.cpp (hunk 17 above)
[the remark this answers is not in the document]
Comment (neobrain) [reply source/loader/gamecard.cpp:1163]: Yeah, my bad. Should be `tuple` indeed.

File: source/loader/gamecard.cpp (hunk 3 above)
Comment (ZeroSkill1) [reply source/loader/gamecard.cpp:1036]: It *is* supported by the format, so I believe it's better to have it implemented. As explained above that's exactly what is done.

File: source/platform/file_formats/ncch.hpp (hunk 10 above)
Comment (ZeroSkill1) [reply source/platform/file_formats/ncch.hpp:538]: Yeah, now that I think about it, it can be confusing like that.

File: source/processes/pxi_fs.cpp (hunk 16 above)
Comment (ZeroSkill1) [reply source/processes/pxi_fs.cpp:461]: It *is* a generic mechanism indeed, and as you said, it's mainly used by the HOME Menu. I'll change the comment.

File: source/loader/gamecard.cpp (hunk 3 above)
Comment (ZeroSkill1) [reply source/loader/gamecard.cpp:1036]: Fair enough. It would indeed simplify things a bunch.

File: source/loader/gamecard.cpp (hunk 2 above)
Comment (ZeroSkill1) [reply source/loader/gamecard.cpp:1177]: I believe I actually tried this before, but if I remember correctly this doesn't actually work for some reason.

File: source/gui-sdl/main.cpp [hunk 19]
```diff
@@ -324,6 +325,36 @@ if (bootstrap_nand) // Experimental system bootstrapper
...
+            auto logo_section = HLE::PXI::FS::NCCHOpenExeFSSection(*frontend_logger, file_context, keydb, std::move(*cxi_partition), 2, std::basic_string_view<uint8_t>(logo_section_name.data(), logo_section_name.size()));
+            
+            std::ofstream logo_file(settings.get<Settings::PathDataDir>() + "/placeholder_logo.bin", std::ios::binary);
+            
+            auto [res, logosize] = logo_section->GetSize(file_context);
+            if (res != HLE::OS::RESULT_OK || !logosize) {
+                throw std::runtime_error("Could not get size of logo section in gamecart executable partition");
+            }
+            
+            auto logobuf = std::make_unique<char>(logosize);
```
[the remark this answers is not in the document]
Comment (ZeroSkill1) [reply source/gui-sdl/main.cpp:351]: Oof. You can tell my main language isn't C++ by now heh.

**Comment by neobrain** [comment]
Ran a minor cleanup pass over the changes. Will give things a final look tomorrow and merge.

**Comment by ZeroSkill1** [comment]
I'm not sure what happened (probably an oversight on my end), but I believe the issue to be `sizeof(dot3dsx_secondary_header)` being used in the tuple comparison, since the secondary header is in  `std::optional`, so `sizeof` returns a large size.

**Comment by ZeroSkill1** [comment]
With this fix it seems to be working as intended now.

File: source/loader/gamecard.cpp [hunk 20]
```diff
@@ -249,58 +271,141 @@ class Adaptor3DSXToNCCH : public HLE::PXI::FS::File {
...
+            using SMDHFlag = FileFormat::SMDH::SMDHFlags;
+
+            icon_data.application_settings.region_flags = 0xFFFFFFFF; // no region lock
+            icon_data.application_settings.flags = Meta::to_underlying(SMDHFlag::Visible | SMDHFlag::DisableSaveBackup);
+            // Give this SMDH a placeholder icon
+            ranges::copy(GameCardConstants::MikageIconSmall, icon_data.small_icon.begin());
+            ranges::copy(GameCardConstants::MikageIconLarge, icon_data.large_icon.begin());
+        } else if (dot3dsxheader.header_size == sizeof(FileFormat::Dot3DSX::Header) + sizeof(FileFormat::Dot3DSX::SecondaryHeader)) {
+            dot3dsx_secondary_header = FileFormat::Dot3DSX::SecondaryHeader{};
+            auto ret = file->Read(context, sizeof(FileFormat::Dot3DSX::Header), sizeof(FileFormat::Dot3DSX::SecondaryHeader), HLE::PXI::FS::FileBufferInHostMemory(dot3dsx_secondary_header));
```
Comment (neobrain) [inline source/loader/gamecard.cpp:304]: There's a pretty bad bug hiding here that I'll fix separately: `HLE::PXI::FS::FileBufferInHostMemory` will write over the `std::optional`, not the actual header data. I'm surprised this is working at all, but perhaps std::optional just happens to store the contained object first (so we aren't overwriting the internal state by pure luck).

`FileBufferInHostMemory` should be more constrained to make this fail to compile, so it's good that we caught it this way. I'll add the fix in a bit.

**Comment by neobrain** [comment]
> With this fix it seems to be working as intended now.

Great! Confirmed working for both 3DSX and CXI files.

Really cool to have the UX constraints around these two formats lifted. Thanks!
